version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/keitaro1020/go-env

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run Unit Tests
          command: |
            make test
